# Generated by Django 2.2.12 on 2021-11-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_monthly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
