# Generated by Django 2.2.12 on 2021-11-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_monthly', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
